TheGrandCosmotel/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WebGames.Libs;
using WebGames.Libs.Games;

namespace WebGames.Controllers
{
    [Authorize(Roles = "player,demo")]
    public class GamesController : Controller
    {
        #region Views
        public ActionResult ActiveGame()
        {
            var customgame = Request.QueryString["customgame"] ?? "";
            var activeGameInfo = GameManager.GetActiveGameInfo(User.Identity.GetUserId(), customgame);

            if (Request.QueryString["showdemo"] == "true")
            {
                activeGameInfo.IsDemo = true;
                activeGameInfo.GameScore = 0;
                activeGameInfo.RemainingTime = 1 * 60; // 1 minute
                activeGameInfo.ActiveLevel = 1;
            }

            return GetPage(activeGameInfo);
        }

        public ActionResult ActiveGameMap()
        {
            var customgame = Request.QueryString["customgame"] ?? "";
            var activeGameInfo = GameManager.GetActiveGameInfo(User.Identity.GetUserId(), customgame);

            return GetPage(activeGameInfo, "Map");
        }

        public ActionResult ActiveExplainer()
        {
            var customgame = Request.QueryString["customgame"] ?? "";
            var activeGameInfo = GameManager.GetActiveGameInfo(User.Identity.GetUserId(), customgame);

            return GetPage(activeGameInfo, "Explainer");
        }

        public ActionResult ActiveGameAfter()
        {
            var status = Request.QueryString["status"] ?? "";

            var customgame = Request.QueryString["customgame"] ?? "";
            var activeGameInfo = GameManager.GetActiveGameInfo(User.Identity.GetUserId(), customgame);

            if (activeGameInfo.ActiveGameDataModel != null)
            {
                var message = activeGameInfo.ActiveGameDataModel.Messages.ContainsKey(status) ? activeGameInfo.ActiveGameDataModel.Messages[status] : "";
                return View("ActiveGameAfter", new Dictionary<string, string>() { { "message", message } });
            }
            else
            {
                return View("NoActiveGame");
            }
        }

        //public ActionResult Group()
        //{
        //    var UserId = User.Identity.GetUserId();

        //    var UserName = User.Identity.GetUserName();

        //    var UserGroup = Group_Manager.GetUserTeam(UserId);

        //    if (UserGroup != null)
        //    {
        //        UserGroup.UsersInGroup = (UserGroup.UsersInGroup ?? new List<string>()).Where(u => u != UserName).ToList();
        //    }
        //    //UserGroup = null;

        //    return View("Group", UserGroup);
        //}
        #endregion

        #region Game3

        public ActionResult Get_Random_Game3_Solution()
        {
            var Rnd = new Random(DateTime.UtcNow.Second);

            var res = new int[4];
            for (int i = 0; i < res.Length; i++)
            {
                var num = 0;
                do
                {
                    num = Rnd.Next(1, 7);
                } while (!res.Contains(num));
                res[i] = num;
            }

            return Json(res, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Game5

        //public ActionResult CheckQuestion(int questionId, int answerIndex)
        //{
        //    var isDemoStr = Request.QueryString["isDemo"] ?? "false";
        //    var isDemo = false;
        //    bool.TryParse(isDemoStr, out isDemo);
        //    var customGameKey = Request.QueryString["customGameKey"] ?? Request.QueryString["customgame"] ?? "";
        //    var UserId = User.Identity.GetUserId();
        //    // Security - Check if Game is the currently active one - cannot set the score for a non active game
        //    var ActiveGameDataModel = GameManager.GetActiveGameInfo(UserId, customGameKey).ActiveGameDataModel;
        //    if (!isDemo && (ActiveGameDataModel== null || ActiveGameDataModel.ActiveGameKey != GameKeys.Questions))
        //    {
        //        return Json(new { success = false, message = "Game is not active" }, JsonRequestBehavior.AllowGet);
        //    }
        //    var res = Questions_Manager.CheckAndSaveQuestionAnswer(UserId, questionId, answerIndex); // Cannot override the score - once is set the done
        //    return Json(new { success = true, isCorrect = res.IsCorrect, correctAnswer = res.CorrectAnswer }, JsonRequestBehavior.AllowGet);
        //}

        //public ActionResult GetPlayerQuestions()
        //{
        //    var res = new List<object>();
        //    try
        //    {
        //        res.AddRange(Questions_Manager.GetPlayerQuestions(User.Identity.GetUserId()).Select(q => new
        //        {
        //            id = q.QuestionId,
        //            question = q.QuestionText,
        //            answer1 = q.Options[0],
        //            answer2 = q.Options[1],
        //            answer3 = q.Options[2],
        //            answer4 = q.Options[3],
        //        }));
        //    }
        //    catch (Exception exc)
        //    {
        //        Logger.Log(exc);
        //    }
        //    return Json(res);
        //}

        #endregion

        public ActionResult Save_Game_Score(int score, long timeStamp, int? level = 1)
        {
            var UserId = User.Identity.GetUserId();

            var customGameKey = Request.QueryString["customGameKey"] ?? Request.QueryString["customgame"] ?? "";
            var ActiveGameKey = "";
            if (customGameKey != "")
            {
                ActiveGameKey = customGameKey;
            }
            else
            {
                var ActiveGameData = GameManager.GetActiveGameInfo(UserId, null).ActiveGameDataModel;
                if (ActiveGameKey != null)
                {
                    ActiveGameKey = ActiveGameData.ActiveGameKey;
                }
            }
            // Security - Check if Game is the currently active one - cannot set the score for a non active game
            if (ActiveGameKey == "" || !GameManager.GameDict.ContainsKey(ActiveGameKey))
            {
                return Json(new { success = false, message = "No Game is Active" }, JsonRequestBehavior.AllowGet);
            }

            GameManager.GameDict[ActiveGameKey].SM.SetUserScore(UserId, score, timeStamp, level.GetValueOrDefault(), EnableOverride: false); // Cannot override the score - once is set the done

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveGameTime(int remainingTime, long timestamp)
        {
            var UserId = User.Identity.GetUserId();
            ActivityManager.SyncPlayedTimeForToday(UserId, remainingTime, timestamp);
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetGameTime()
        {
            var UserId = User.Identity.GetUserId();
            var res = UserGameManager.GetUserRemainingTime(User.Identity.GetUserId());
            return Json(new { success = true, time = res }, JsonRequestBehavior.AllowGet);
        }

        // Helpers //
        private ActionResult GetPage(ActiveUserGameInfo gameInfo, string Page = "")
        {
            ActionResult ViewRes = null;
            // Active game was found
            if (gameInfo.ActiveGameDataModel != null)
            {
                // No remaining time
                if (gameInfo.RemainingTime <= 0)
                {
                    ViewRes = RedirectToAction("ActiveGameAfter", new { status = "outoftime" });
                } // no available levels
                else if (gameInfo.AvailableLevels > 0 && gameInfo.AvailableLevels < gameInfo.ActiveLevel)
                {
                    ViewRes = RedirectToAction("ActiveGameAfter", new { status = "success" });
                }
                else
                {
                    string ViewPageToDisplay = gameInfo.Folder;
                    if (Page != "")
                    {
                        ViewPageToDisplay += $"/{Page}";
                    }
                    else // it's the game so use the PageFolder for the file
                    {
                        ViewPageToDisplay += $"/{gameInfo.Page}";

                        // If level is on its own page
                        if (gameInfo.LevelAsPage)
                        {
                            // use level specific page
                            ViewPageToDisplay += $"-{gameInfo.ActiveLevel}";
                        }
                    }

                    ViewRes = View(ViewPageToDisplay, gameInfo);
                }
            }
            else
            {
                // Nothing was found
                ViewRes = View("NoActiveGame");
            }

            return ViewRes;
        }
    }
}

TheGrandCosmotel/Controllers/HomeController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebGames.Models.ViewModels;
using Microsoft.AspNet.Identity;
using WebGames.Libs.Games.Games;
using WebGames.Libs.Games;

namespace WebGames.Controllers
{
    public class HomeController : Controller
    {     
        public HomeController()
        {
        }

        public HomeController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account"); 
            }
            ViewBag.Link = TempData["ViewBagLink"];

            if (User.IsInRole("sysadmin") || User.IsInRole("admin"))
            {

                return RedirectToAction("Index", "Dashboard");
            }
            var UserId = User.Identity.GetUserId();
            var model = new HomeIndexViewModel()
            {
                IsWinner = Winner_Manager.IsUserWinner(UserId),
                DailyData = GameDayScheduleManager.GetActiveDailyData(DateTime.UtcNow)
            };

            return View(model);
        }

        public ActionResult Info()
        {
            return View();
        }

        public ActionResult TnC()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

    }
}

TheGrandCosmotel/Views/Home/Index.cshtml
@model WebGames.Models.ViewModels.HomeIndexViewModel
@section Scripts {

}


@*<div class="jumbotron">
    <img src="/Content/images/cosmotelogo.png" id="cosmologo">

        <h1> Hello @User.Identity.Name </h1>
        <p><a class="btn btn-primary btn-lg" href="@Url.Action("Group", "Games")" role="button">Start Playing</a></p>

    </div>*@

<div class="wrapper">
    <div class="screen screen1">

        <div class="messageoftheday">
            <h1>Το ταξίδι σου στον κόσμο του μαγεμένου τσίρκου ολοκληρώθηκε!</h1>
            <p>Η μεγάλη στιγμή για σένα και την ομάδα* σου έφτασε… </p>
            <p>Μπές στο cosmoplay.gr την Πέμπτη 18 Μαΐου για να μάθεις εάν προκρίθηκες στον Τριήμερο Τελικό στο Πόρτο Χέλι! (26-28 Μαΐου).</p>
            <br>
            <p class="explain" style="font-size: 12px;">* Υπενθυμίζουμε ότι οι ομάδες του τελικού διαμορφώθηκαν βάση ατομικής και ομαδικής κατάταξης και λαμβάνοντας υπόψιν την εύρυθμη λειτουργία των καταστημάτων.</p>
        </div>

        @*@if (Model.IsWinner)
        {

            <div class="messageoftheday">
                <h1>Συγχαρητήρια!</h1>
                <p>Έχεις προκριθεί στον τριήμερο τελικό του Cosmoplay-Circus 2017 στο Πόρτο Χέλι 26-28 Μαΐου!</p>
                <p>Μια αξέχαστη εμπειρία σε περιμένει!</p>
                <p>Περισσότερες πληροφορίες μπορείς να δεις 
                    <a style="font-weight: bold;text-decoration: underline;" href="/Files/GetWinnerInfo">
                        εδώ</a>, ενώ μέσα στην ημέρα θα σου σταλεί αναλυτική ενημέρωση και στο εταιρικό σου email.
                </p>
                <br>
                <p class="explain" style="font-size: 12px;">* Υπενθυμίζουμε ότι οι ομάδες του τελικού διαμορφώθηκαν βάση ατομικής και ομαδικής κατάταξης και λαμβάνοντας υπόψιν την εύρυθμη λειτουργία των καταστημάτων.</p>
            </div>

        }
        else
        {
            <div class="messageoftheday">
                <h1>Ευχαριστούμε για τη συμμετοχή σου!</h1>
                <p>Ελπίζουμε να απόλαυσες το ταξίδι σου στον κόσμο του μαγεμένου τσίρκου.</p>
                <p>Δυστυχώς δεν κατάφερες να προκριθείς στον τριήμερο τελικό στο Πόρτο Χέλι.</p>
                <br>
                <p class="explain" style="font-size: 12px;">* Υπενθυμίζουμε ότι οι ομάδες του τελικού διαμορφώθηκαν βάση ατομικής και ομαδικής κατάταξης και λαμβάνοντας υπόψιν την εύρυθμη λειτουργία των καταστημάτων.</p>
            </div>
        }*@

    </div>
</div>

TheGrandCosmotel/Views/Home/Info.cshtml
<div class="paper">
<p>Φανταχτερά κοστούμια, εντυπωσιακοί ακροβάτες, ριψοκίνδυνοι θηριοδαμαστές, κομπέρ, παλιάτσοι, μάγοι και μάντισσες, παράξενα πλάσματα και θεαματικά παιχνίδια… Η ατμόσφαιρα του φετινού Cosmoplay έχει κάτι φαντασμαγορικό και μυστηριώδες!</p>
<p>Καλώς ήρθατε στο <strong>COSMOPLAY CIRCUS!</strong></p>
<p>To σενάριο απλό αλλά μυστηριώδες…</p>
<p>ΤΙ ΠΡΕΠΕΙ ΝΑ ΚΑΝΕΙΣ…</p>
<p>Για τα ταξιδέψεις στον κόσμο του μαγεμένου τσίρκου θα πρέπει <strong>αρχικά να κάνεις την εγγραφή σου μέχρι και την Τετάρτη 26 Απριλίου 2017.</strong></p>
<p style="font-style: italic">Για την καλύτερη πλοήγηση στο παιχνίδι απαιτούνται οι παρακάτω browsers:</p>
<p style="font-style: italic">PC: Edge, Chrome, Firefox</p>
<p style="font-style: italic"contenteditable="">Tablet &amp; κινητό: chrome, safari</p>
<p><strong>Το Ηλεκτρονικό Παιχνίδι θα ξεκινήσει την Πέμπτη 27 Απριλίου</strong> και θα διαρκέσει έως και τη <strong>Δευτέρα 15 Μαΐου, και περιλαμβάνει 6 διαφορετικά παιχνίδια/πίστες</strong>. Το κάθε παιχνίδι είναι ανοιχτό για 3 ημέρες, διαρκεί 5 λεπτά και αντιστοιχεί σε ένα σημείο του μαγεμένου CIRCUS! Μπορείς να παίζεις καθημερινά αλλά μια φορά ημερησίως και μόνο για 5 λεπτά, κάνοντας &nbsp;login στο site. Στόχος κάθε πίστας είναι να ολοκληρώσεις το παιχνίδι στον καλύτερο δυνατό χρόνο και πριν περάσουν τα 5 λεπτά. <span style="text-decoration: underline">Θυμίζουμε ότι φέτος μπορείς να παίρνεις μέρος στο παιχνίδι από τον προσωπικό ή εταιρικό υπολογιστή σου καθώς και από το tablet ή το κινητό σου.</span></p>
<p>Στα τέσσερα πρώτα παιχνίδια παίζεις ατομικά, ενώ στα δύο τελευταία, βάσει καλύτερης βαθμολογίας, χωρίζεστε σε ομάδες και παίζεις συλλέγοντας πόντους για την ομάδα σου!</p>
<p>Αν τα καταφέρεις, θα βρεθείς στον μεγάλο τελικό και θα γνωρίσεις το Circus από κοντά!</p>
<p>Και θυμήσου πριν ξεκινήσεις να διαβάσεις τους αναλυτικούς όρους και προϋποθέσεις συμμετοχής στο παιχνίδι!</p>
<p>Αν αντιμετωπίσεις οποιοδήποτε πρόβλημα μπορείς να απευθυνθείς:</p>
<p>Για τεχνική υποστήριξη: <a href="mailto:support@cosmoplay.gr">support@cosmoplay.gr</a></p>
<p>Για οποιαδήποτε άλλη πληροφορία: <a href="mailto:cosmoplay@cosmoplay.gr">cosmoplay@cosmote.gr</a></p>
<p>Καλή διασκέδαση και καλή επιτυχία!</p>
<br>
</div>